# Tmux plugin manager https://github.com/tmux-plugins/tpm
".local/share/tmux/plugins/tpm":
  exact: true
  type: "archive"
  url: "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
  refreshPeriod: "168h"
  stripComponents: 1

# Vim-plug plugin manager
".local/share/nvim/site/autoload/plug.vim":
  type: "file"
  url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod: "168h"

# ZSH plugins
".local/share/zsh/plugins/zsh-nvm.plugin.zsh":
  type: "file"
  url: "https://github.com/lukechilds/zsh-nvm/raw/master/zsh-nvm.plugin.zsh"
  refreshPeriod: "168h"

