# Tmux plugin manager https://github.com/tmux-plugins/tpm
".config/tmux/plugins/tpm":
  exact: true
  type: "archive"
  url: "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
  refreshPeriod: "168h"
  stripComponents: 1

# ZSH plugins
".local/share/zsh/plugins/zsh-nvm.plugin.zsh":
  type: "file"
  url: "https://github.com/lukechilds/zsh-nvm/raw/master/zsh-nvm.plugin.zsh"
  refreshPeriod: "168h"
".local/share/zsh/plugins/fzf-tab":
  exact: true
  type: "archive"
  url: "https://github.com/Aloxaf/fzf-tab/archive/refs/heads/master.zip"
  refreshPeriod: "168h"
  stripComponents: 1
".local/share/zsh/plugins/zsh-autosuggestions.zsh":
  type: "file"
  url: "https://github.com/zsh-users/zsh-autosuggestions/raw/master/zsh-autosuggestions.zsh"
  refreshPeriod: "168h"
